ACE_INHIBITORS_TERMS = [
    "fosinopril",
    "fosinopril sodium",
    "monopril",
    "ramipril",
    "altace",
    "captopril",
    "capoten",
    "moexipril",
    "univasc",
    "lisinopril",
    "zestril",
    "prinivil",
    "enalapril",
    "vasotec",
    "epaned",
    "quinapril",
    "accupril",
    "trandolapril",
    "mavik",
    "gopten",
    "odrik",
    "benazepril",
    "lotensin",
    "perindopril",
    "aceon",
]
