BETA_BLOCKERS_TERMS = [
    "betaxolol",
    "kerlone",
    "betoptic",
    "acebutolol",
    "sectral",
    "atenolol",
    "tenormin",
    "metoprolol",
    "metoprolol_succinate",
    "toprol-xl",
    "metoprolol_tartrate",
    "lopressor",
    "metoprolol_succinate_er",
    "metoprolol_tartrate",
    "dutoprolol",
    "nebivolol",
    "bystolic",
    "bisoprolol",
    "zebeta",
    "esmolol",
    "brevibloc",
    "propranolol",
    "innopran xl",
    "inderal",
    "inderal la",
    "nadolol",
    "corgard",
    "carvedilol",
    "coreg",
    "coreg cr",
    "labetalol",
    "normodyne",
    "trandate",
    "timolol",
    "blocadren",
    "timoptic",
    "istalol",
    "betimol",
    "carteolol",
    "cartrol",
    "penbutolol",
    "levatol",
    "pindolol",
    "visken",
]
